language: go

matrix:
  include:
  -  os: linux
     sudo: required
     services:
       - docker
     before_install:
	 - sudo add-apt-repository -y ppa:projectatomic/ppa
	 - sudo apt-get update
	 - sudo podman
  -  os: osx

notifications:
  email: false

install:
  # NOTE: The (brew update) should not be necessary, and slows things down;
  # we include it as a workaround for https://github.com/Homebrew/brew/issues/3299
  # ideally Travis should bake the (brew update) into its images
  # (https://github.com/travis-ci/travis-ci/issues/8552 ), but thatâ€™s only going
  # to happen around November 2017 per https://blog.travis-ci.com/2017-10-16-a-new-default-os-x-image-is-coming .
  # Remove the (brew update) at that time.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install gpgme ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then hack/travis_osx.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make vendor-in-container && ./hack/tree_status.sh && make check ; fi
